<?php
/** @var $this Perpetto_Perpetto_Block_Adminhtml_System_Config_Form_Campaigns */
?>
<div class="perpetto">
    <?php echo $this->getHeaderHtml(); ?>
    <?php if ($this->showLinks()): ?>
        <table cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <td style="padding-right: 10px;">
                    <div class="entry-edit entry-edit-box">
                        <div class="entry-edit-head">
                            <h4><?php echo $this->__('Emails Dashboard'); ?></h4>
                        </div>
                        <div class="fieldset">
                            <p><?php echo $this->__('View your Emails Dashboard to see the results from Email Campaigns.'); ?></p>
                            <a class="button" href="<?php echo $this->getDashboardUrl() ?>"
                               target="_blank"><?php echo $this->__('Emails Dashboard'); ?></a>
                        </div>
                    </div>
                </td>
                <td style="padding-right: 10px; padding-left: 10px;">
                    <div class="entry-edit entry-edit-box">
                        <div class="entry-edit-head">
                            <h4><?php echo $this->__('Ask-Us-Anything Support'); ?></h4>
                        </div>
                        <div class="fieldset">
                            <p><?php echo $this->__('Ask us anything you might need to know. We are here to help.'); ?></p>
                            <a class="button" href="<?php echo $this->getContactsUrl() ?>"
                               target="_blank"><?php echo $this->__('Get In Touch'); ?></a>
                        </div>
                    </div>
                </td>
                <td style="padding-left: 10px;">
                    <div class="entry-edit entry-edit-box">
                        <div class="entry-edit-head">
                            <h4><?php echo $this->getBillingTitle() ?></h4>
                        </div>
                        <div class="fieldset">
                            <p><?php echo $this->getBillingText() ?></p>
                            <a class="button" href="<?php echo $this->getBillingUrl() ?>"
                               target="_blank"><?php echo $this->getBillingButtonText() ?></a>
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <div class="clear"></div>
    <?php endif ?>
    <?php if ($this->showCampaigns()): ?>
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?php echo $this->__('Email Campaigns'); ?></h4>
            </div>
            <div class="fieldset">
                <p class="box-left"><?php echo $this->__('Here you can see what email campaigns are configured in your
                account. You can send a test email to your Perpetto account email, or edit the campaigns in the
                Perpetto administration area using the "Edit Email Campaigns" button.'); ?></p>

                <div class="box-right align-right">
                    <a class="button" href="<?php echo $this->getEmailCampaignsUrl(); ?>"
                       target="_blank"><?php echo $this->__('Edit Email Campaigns'); ?></a>
                </div>

                <div class="clear"></div>

                <?php foreach ($this->getEmailCampaigns() as $campaign): ?>
                    <?php
                    $emails = (array)$campaign['emails'];
                    $emailsCount = count($emails);
                    ?>
                    <table class="perpetto-slots" cellpadding="0" cellspacing="0" width="100%">
                        <tbody>
                        <tr>
                            <th rowspan="<?php echo $emailsCount + 1 ?>"><?php echo $this->escapeHtml($campaign['name']) ?></th>
                            <th><?php echo $this->__('Email Title'); ?></th>
                            <th><?php echo $this->__('Email Subject'); ?></th>
                            <th colspan="2"><?php echo $this->__('Status'); ?></th>
                        </tr>
                        <?php foreach ($emails as $email): /** @var $slot Perpetto_Perpetto_Model_Slot */ ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($email['title']) ?></td>
                                <td><?php echo $this->escapeHtml($email['subject']) ?></td>
                                <td><?php echo $this->escapeHtml(ucwords($email['status'])); ?></td>
                                <td><a href="<?php echo $this->getEmailCampaignTestUrl($campaign['id'],
                                        $email['id']) ?>"><?php echo $this->__('Send Test Email') ?></a></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                <?php endforeach; ?>
            </div>
        </div>
    <?php endif ?>
    <?php echo $this->getChildHtml('form_after'); ?>
</div>
<script type="text/javascript">
    $$('#content .content-header button').each(function (item) {
        item.remove();
    });
</script>
